[package]
name = "rusty-os"
version = "0.1.0"
authors = ["Rafael Boy <rafaboyr95@gmail.com>", "Roberto Valenzuela <valenzuelarober@gmail.com>"]
edition = "2018"
description = "Rusty-OS is a simple kernel for embedded systems written in Rust"
documentation = "https://github.com/roemvaar/rusty-os/tree/main/docs"
readme = "https://github.com/roemvaar/rusty-os/blob/main/README.md"
repository = "https://github.com/roemvaar/rusty-os/tree/main/src"
homepage = "https://github.com/roemvaar/rusty-os"
license = "MIT"
keywords = ["kernel"]
categories = ["embedded"]

[dependencies]
