[package]
name = "rusty-os"
version = "0.1.0"
authors = ["Rafael Boy <rafaboyr95@gmail.com>", "Roberto Valenzuela <valenzuelarober@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
